name: checksum-scripts-main

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      
      - name: Mirror at Codeberg
        uses: spyoungtech/mirror-action@master
        with:
          REMOTE: git@codeberg.org:CTemplar/checksum-scripts.git
          GIT_SSH_PRIVATE_KEY: ${{ secrets.CODEBERG_SSH_PRIVATE_KEY }}
          GIT_SSH_NO_VERIFY_HOST: "true"
